// Mocks generated by Mockito 5.3.0 from annotations
// in app/test/service_tests/api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app/models/User.dart' as _i4;
import 'package:app/services/auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationService extends _i1.Mock
    implements _i2.AuthenticationService {
  MockAuthenticationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set token(String? _token) =>
      super.noSuchMethod(Invocation.setter(#token, _token),
          returnValueForMissingStub: null);
  @override
  bool get isAuthenticated => (super
          .noSuchMethod(Invocation.getter(#isAuthenticated), returnValue: false)
      as bool);
  @override
  _i3.Future<bool> isUserLoggedIn() =>
      (super.noSuchMethod(Invocation.method(#isUserLoggedIn, []),
          returnValue: _i3.Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<dynamic> syncUser() =>
      (super.noSuchMethod(Invocation.method(#syncUser, []),
          returnValue: _i3.Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> sendSignInWithEmailLink(
          String? email, String? name, bool? acceptNewletter) =>
      (super.noSuchMethod(
          Invocation.method(
              #sendSignInWithEmailLink, [email, name, acceptNewletter]),
          returnValue: _i3.Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> login(String? email, String? emailToken) =>
      (super.noSuchMethod(Invocation.method(#login, [email, emailToken]),
          returnValue: _i3.Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  bool logout() =>
      (super.noSuchMethod(Invocation.method(#logout, []), returnValue: false)
          as bool);
  @override
  _i3.Future<_i4.User>? getUser(String? token) =>
      (super.noSuchMethod(Invocation.method(#getUser, [token]))
          as _i3.Future<_i4.User>?);
  @override
  _i3.Future<bool> updateUserDetails(
          {String? name, DateTime? dob, String? orgCode}) =>
      (super.noSuchMethod(
          Invocation.method(#updateUserDetails, [],
              {#name: name, #dob: dob, #orgCode: orgCode}),
          returnValue: _i3.Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<dynamic> deleteUserAccount() =>
      (super.noSuchMethod(Invocation.method(#deleteUserAccount, []),
          returnValue: _i3.Future<dynamic>.value()) as _i3.Future<dynamic>);
}
