// Mocks generated by Mockito 5.3.0 from annotations
// in app/test/service_tests/causes_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/services/api_service.dart' as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeApiException_1 extends _i1.SmartFake implements _i3.ApiException {
  _FakeApiException_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
          returnValue: _FakeClient_0(this, Invocation.getter(#client)))
      as _i2.Client);
  @override
  set client(_i2.Client? _client) =>
      super.noSuchMethod(Invocation.setter(#client, _client),
          returnValueForMissingStub: null);
  @override
  String get baseUrl =>
      (super.noSuchMethod(Invocation.getter(#baseUrl), returnValue: '')
          as String);
  @override
  set baseUrl(String? _baseUrl) =>
      super.noSuchMethod(Invocation.setter(#baseUrl, _baseUrl),
          returnValueForMissingStub: null);
  @override
  String get baseUrlPath =>
      (super.noSuchMethod(Invocation.getter(#baseUrlPath), returnValue: '')
          as String);
  @override
  set baseUrlPath(String? _baseUrlPath) =>
      super.noSuchMethod(Invocation.setter(#baseUrlPath, _baseUrlPath),
          returnValueForMissingStub: null);
  @override
  _i3.ApiException getExceptionForResponse(_i2.Response? response) => (super
          .noSuchMethod(Invocation.method(#getExceptionForResponse, [response]),
              returnValue: _FakeApiException_1(this,
                  Invocation.method(#getExceptionForResponse, [response])))
      as _i3.ApiException);
  @override
  Map<String, String> getRequestHeaders() =>
      (super.noSuchMethod(Invocation.method(#getRequestHeaders, []),
          returnValue: <String, String>{}) as Map<String, String>);
  @override
  _i4.Future<Map<dynamic, dynamic>> getRequest(String? path,
          {Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
              Invocation.method(#getRequest, [path], {#params: params}),
              returnValue:
                  _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<List<Map<String, dynamic>>> getListRequest(String? path,
          {Map<String, dynamic>? params, int? limit = 5}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getListRequest, [path], {#params: params, #limit: limit}),
              returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i4.Future<List<Map<String, dynamic>>>);
  @override
  _i4.Future<T> getModelRequest<T>(
          String? path, _i3.JsonDeserializer<T>? deserializer,
          {Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getModelRequest, [path, deserializer], {#params: params}),
          returnValue: _i4.Future<T>.value(null)) as _i4.Future<T>);
  @override
  _i4.Future<List<T>> getModelListRequest<T>(
          String? path, _i3.JsonDeserializer<T>? deserializer,
          {Map<String, dynamic>? params, int? limit = 5}) =>
      (super.noSuchMethod(
              Invocation.method(#getModelListRequest, [path, deserializer],
                  {#params: params, #limit: limit}),
              returnValue: _i4.Future<List<T>>.value(<T>[]))
          as _i4.Future<List<T>>);
  @override
  _i4.Future<Map<String, dynamic>> postRequest(String? path,
          {Map<String, dynamic>? body}) =>
      (super.noSuchMethod(
              Invocation.method(#postRequest, [path], {#body: body}),
              returnValue:
                  _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> putRequest(String? path,
          {Map<String, dynamic>? body}) =>
      (super.noSuchMethod(Invocation.method(#putRequest, [path], {#body: body}),
              returnValue:
                  _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i4.Future<Map<dynamic, dynamic>>);
  @override
  _i4.Future<Map<dynamic, dynamic>> deleteRequest(String? path) =>
      (super.noSuchMethod(Invocation.method(#deleteRequest, [path]),
              returnValue:
                  _i4.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i4.Future<Map<dynamic, dynamic>>);
}
