// Mocks generated by Mockito 5.3.0 from annotations
// in app/test/setup/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i7;
import 'dart:typed_data' as _i8;

import 'package:app/services/api_service.dart' as _i5;
import 'package:http/http.dart' as _i4;
import 'package:http/src/base_request.dart' as _i9;
import 'package:http/src/response.dart' as _i2;
import 'package:http/src/streamed_response.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i3.StreamedResponse {
  _FakeStreamedResponse_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeClient_2 extends _i1.SmartFake implements _i4.Client {
  _FakeClient_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeApiException_3 extends _i1.SmartFake implements _i5.ApiException {
  _FakeApiException_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i4.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
                  this, Invocation.method(#head, [url], {#headers: headers}))))
          as _i6.Future<_i2.Response>);
  @override
  _i6.Future<_i2.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
                  this, Invocation.method(#get, [url], {#headers: headers}))))
          as _i6.Future<_i2.Response>);
  @override
  _i6.Future<_i2.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i7.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#post, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
                  this,
                  Invocation.method(#post, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i6.Future<_i2.Response>);
  @override
  _i6.Future<_i2.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i7.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#put, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
                  this,
                  Invocation.method(#put, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i6.Future<_i2.Response>);
  @override
  _i6.Future<_i2.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i7.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#patch, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
                  this,
                  Invocation.method(#patch, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i6.Future<_i2.Response>);
  @override
  _i6.Future<_i2.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i7.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#delete, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
                  this,
                  Invocation.method(#delete, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i6.Future<_i2.Response>);
  @override
  _i6.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: _i6.Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<_i8.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: _i6.Future<_i8.Uint8List>.value(_i8.Uint8List(0)))
          as _i6.Future<_i8.Uint8List>);
  @override
  _i6.Future<_i3.StreamedResponse> send(_i9.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue: _i6.Future<_i3.StreamedResponse>.value(
                  _FakeStreamedResponse_1(
                      this, Invocation.method(#send, [request]))))
          as _i6.Future<_i3.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Client get client => (super.noSuchMethod(Invocation.getter(#client),
          returnValue: _FakeClient_2(this, Invocation.getter(#client)))
      as _i4.Client);
  @override
  set client(_i4.Client? _client) =>
      super.noSuchMethod(Invocation.setter(#client, _client),
          returnValueForMissingStub: null);
  @override
  String get baseUrl =>
      (super.noSuchMethod(Invocation.getter(#baseUrl), returnValue: '')
          as String);
  @override
  set baseUrl(String? _baseUrl) =>
      super.noSuchMethod(Invocation.setter(#baseUrl, _baseUrl),
          returnValueForMissingStub: null);
  @override
  String get baseUrlPath =>
      (super.noSuchMethod(Invocation.getter(#baseUrlPath), returnValue: '')
          as String);
  @override
  set baseUrlPath(String? _baseUrlPath) =>
      super.noSuchMethod(Invocation.setter(#baseUrlPath, _baseUrlPath),
          returnValueForMissingStub: null);
  @override
  _i5.ApiException getExceptionForResponse(_i2.Response? response) => (super
          .noSuchMethod(Invocation.method(#getExceptionForResponse, [response]),
              returnValue: _FakeApiException_3(this,
                  Invocation.method(#getExceptionForResponse, [response])))
      as _i5.ApiException);
  @override
  Map<String, String> getRequestHeaders() =>
      (super.noSuchMethod(Invocation.method(#getRequestHeaders, []),
          returnValue: <String, String>{}) as Map<String, String>);
  @override
  _i6.Future<Map<dynamic, dynamic>> getRequest(String? path,
          {Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
              Invocation.method(#getRequest, [path], {#params: params}),
              returnValue:
                  _i6.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i6.Future<Map<dynamic, dynamic>>);
  @override
  _i6.Future<List<Map<String, dynamic>>> getListRequest(String? path,
          {Map<String, dynamic>? params, int? limit = 5}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getListRequest, [path], {#params: params, #limit: limit}),
              returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i6.Future<List<Map<String, dynamic>>>);
  @override
  _i6.Future<T> getModelRequest<T>(
          String? path, _i5.JsonDeserializer<T>? deserializer,
          {Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getModelRequest, [path, deserializer], {#params: params}),
          returnValue: _i6.Future<T>.value(null)) as _i6.Future<T>);
  @override
  _i6.Future<List<T>> getModelListRequest<T>(
          String? path, _i5.JsonDeserializer<T>? deserializer,
          {Map<String, dynamic>? params, int? limit = 5}) =>
      (super.noSuchMethod(
              Invocation.method(#getModelListRequest, [path, deserializer],
                  {#params: params, #limit: limit}),
              returnValue: _i6.Future<List<T>>.value(<T>[]))
          as _i6.Future<List<T>>);
  @override
  _i6.Future<Map<String, dynamic>> postRequest(String? path,
          {Map<String, dynamic>? body}) =>
      (super.noSuchMethod(
              Invocation.method(#postRequest, [path], {#body: body}),
              returnValue:
                  _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i6.Future<Map<String, dynamic>>);
  @override
  _i6.Future<Map<dynamic, dynamic>> putRequest(String? path,
          {Map<String, dynamic>? body}) =>
      (super.noSuchMethod(Invocation.method(#putRequest, [path], {#body: body}),
              returnValue:
                  _i6.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i6.Future<Map<dynamic, dynamic>>);
  @override
  _i6.Future<Map<dynamic, dynamic>> deleteRequest(String? path) =>
      (super.noSuchMethod(Invocation.method(#deleteRequest, [path]),
              returnValue:
                  _i6.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i6.Future<Map<dynamic, dynamic>>);
}
