#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/piotrstanny/flutterdev/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/piotrstanny/AndroidStudioProjects/now-u-app"
export "FLUTTER_TARGET=/Users/piotrstanny/AndroidStudioProjects/now-u-app/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_BUILD_NAME=1.1.9"
export "FLUTTER_BUILD_NUMBER=33"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/piotrstanny/AndroidStudioProjects/now-u-app/.dart_tool/package_config.json"
