/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _actionIcons = 'ActionIcons';

  static const _customIcons = 'CustomIcons';

  static const dynamic _kFontPkg = null;

  static const IconData home =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campaign =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData icon_vol_1 =
      IconData(0xe80d, fontFamily: _actionIcons, fontPackage: _kFontPkg);
  static const IconData icon_raise_awareness_01_01 =
      IconData(0xe80e, fontFamily: _actionIcons, fontPackage: _kFontPkg);
  static const IconData icon_petition_01 =
      IconData(0xe80f, fontFamily: _actionIcons, fontPackage: _kFontPkg);
  static const IconData icon_learning_01 =
      IconData(0xe810, fontFamily: _actionIcons, fontPackage: _kFontPkg);
  static const IconData icon_fundraise_01 =
      IconData(0xe811, fontFamily: _actionIcons, fontPackage: _kFontPkg);
  static const IconData icon_donate_01 =
      IconData(0xe812, fontFamily: _actionIcons, fontPackage: _kFontPkg);
  static const IconData icon_contact_01 =
      IconData(0xe813, fontFamily: _actionIcons, fontPackage: _kFontPkg);
  static const IconData icon_connect_01 =
      IconData(0xe814, fontFamily: _actionIcons, fontPackage: _kFontPkg);
  static const IconData icon_behaviour_01 =
      IconData(0xe815, fontFamily: _actionIcons, fontPackage: _kFontPkg);
  static const IconData icon_quiz_01 =
      IconData(0xe816, fontFamily: _actionIcons, fontPackage: _kFontPkg);
  static const IconData icon_protest_01 =
      IconData(0xe817, fontFamily: _actionIcons, fontPackage: _kFontPkg);
}
